### ISSUE TITLE
词汇表

### ISSUE THREAD

**Issue by QC-L** [slidevjs/docs-cn#14]
> 这里用于讨论哪些词汇，如何翻译以及统一。

| 术语 | 译文 |
| :---: | :---:|
| Section | 章节 |
| eject | 弹出 |

**Comment by QC-L** [comment]
关于 Front Matter 的翻译，我搜了很多词典，感觉扉页会比较恰当些。

具体参考：https://dict.zhuaniao.com/en/front+matter/

**Comment by antfu** [comment]
> 讨论：关于 Front Matter 的翻译
> 
> 我搜了很多词典，感觉**扉页**会比较恰当些。
> 
> 具体参考：[dict.zhuaniao.com/en/front+matter](https://dict.zhuaniao.com/en/front+matter/)

嗯嗯，可以。但是感觉这个词在这个情景下，有些专有名词的感觉。建议在每篇文档第一次出现时，备注一下英文。

**Comment by Notobey** [comment]
讨论：关于 The Problems 的翻译

The Problems是guide章节中why.md的二级标题，如下图：
![image](https://user-images.githubusercontent.com/36811055/118358969-becfe080-b5b3-11eb-908c-73efb026ef0a.png)

此处感觉更主要的是描述Slidev的优势，所以我想翻译为：优势所在

不知道是否妥当？

**Comment by antfu** [comment]
嗯，章节的内容和原本定的标题的确不太符合了，这里把二级标题直接拿掉好了，我英文的文档也改一下

**Comment by Notobey** [comment]
> 嗯，章节的内容和原本定的标题的确不太符合了，这里把二级标题直接拿掉好了，我英文的文档也改一下

哈哈，好的

**Comment by ArcherGu** [comment]
@antfu 目前我是将 Front Matter 翻译修改为了 “扉页“，说明的地方按照 ”扉页处（文件顶部）“这样的方式进行了解释。尽管我个人的中文理解里 “扉页” 是一个独立的页面，或者说是一个独立的文件，我对此保留这个想法。😂

**Comment by QC-L** [comment]
@ArcherGu 你觉得怎么翻译比较好嘞？可以说说你的想法，讨论下

**Comment by ArcherGu** [comment]
@QC-L 我找了一些资料，最后我觉得 front-matter 或许不需要进行翻译，它是指markdown文件的顶部部分，就像我们直接说markdown，而不是将其翻译为 “标记下”，作为一个开发者之间约定俗称的名称，front-matter应该也没有翻译的必要，只需要在第一次出现的时候进行一下说明即可。 我觉得目前应该也没有一个比较优雅的词来翻译它...

**Comment by QC-L** [comment]
@ArcherGu 页头？怎么样？

**Comment by Ivocin** [comment]
> @QC-L 我找了一些资料，最后我觉得 front-matter 或许不需要进行翻译，它是指markdown文件的顶部部分，就像我们直接说markdown，而不是将其翻译为 “标记下”，作为一个开发者之间约定俗称的名称，front-matter应该也没有翻译的必要，只需要在第一次出现的时候进行一下说明即可。 我觉得目前应该也没有一个比较优雅的词来翻译它...

我的建议是能翻译尽量翻译，毕竟中文文档中汉语更有意义，而 front matter 虽然是一个专有名词，指代 markdown 的头部配置部分，但是其英文也并不出名，做不到和 markdown 一样的级别，所以尽量翻译一个合适的中文词汇比较好。

确实找到一个适当的中文词汇比较难，需要琢磨。

**Comment by ArcherGu** [comment]
可以一起琢磨一下，说不定以后大家都这样来翻译了，史无前例的翻译，想想就有点激动...

**Comment by ArcherGu** [comment]
> @ArcherGu 页头？怎么样？

页头似乎和 “page header” 冲突了...尽量给它一个自己的名称吧，再不行我们就组合创造一个新的词。

**Comment by Megrax** [comment]
讨论：关于 eject 的翻译

在 themes 章节中的 use.md 中有一段对 Eject Theme 的说明，如下图：

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/56376387/118385653-76f89a00-b643-11eb-83d5-1a5c03a148b4.png">

我感觉这个 eject 不太好翻译，在网上查阅了一下，有人在博文里会把 eject 翻译为 “弹出”，但是我觉得 “弹出主题” 听起来有点怪怪的，我觉得可能 “移出”、“取出” 或 “抽出” 可能会比较好，想问问大家的看法🤔

**Comment by antfu** [comment]
> eject

这个词来源于 CRA，有趣的是他们的文档也没有进行翻译 😂 http://www.html.cn/create-react-app/docs/available-scripts/#npm-run-eject 我个人觉得可能 “释出” 在这里会比较好一些

**Comment by QC-L** [comment]
> > eject
> 
> 这个词来源于 CRA，有趣的是他们的文档也没有进行翻译 😂 http://www.html.cn/create-react-app/docs/available-scripts/#npm-run-eject 我个人觉得可能 “释出” 在这里会比较好一些

用 **释放** 如何
