### ISSUE TITLE
本地构建文档，pnpm i 无法安装依赖

### ISSUE THREAD

**Issue by ArcherGu** [slidevjs/docs-cn#36]
Hi，抱歉，我对pnpm不是很熟悉，我试着在本地跑一下文档，但是发现切换到`site`分支后，直接运行`pnpm install`或者`pnpm i`以后终端只是打印了一句:
```
Scope: all 10 workspace projects
```
然后就什么都没有发生了，依赖没有安装。我大概看了下pnpm workspace的意思，目前只能理解这是一种将各类子包放在一个仓库里，然后通过workspace进行内部依赖加载的方法。

**Comment by ArcherGu** [comment]
我在wls里和MacOS上发现可以正常用pnpm安装依赖，不知道什么原因，目前我只能甩锅给windows.

**Comment by QC-L** [comment]
解决了？

**Comment by ArcherGu** [comment]
> 解决了？

嗯，我切换到wsl里以后再用pnpm安装依赖就可以了，在powershell里直接就打印了一句`Scope: all 10 workspace projects`，然后什么都没有了。
